eleve_homepage:
    path:     /
    defaults: { _controller: EleveBundle:Default:index }

delete:
    path:     /delete{id}
    defaults: { _controller: EleveBundle:eleve:delete }

delC:
    path:     /delC{id}
    defaults: { _controller: EleveBundle:Classe:deleteC }
show2:
        path:     /show2
        defaults: { _controller: EleveBundle:Carnet:show2 }