eleve_carnet:
    resource: "@EleveBundle/Controller/CarnetController.php"
    type:     annotation

eleve_classe:
    resource: "@EleveBundle/Controller/ClasseController.php"
    type:     annotation

eleve_eleve:
    resource: "@EleveBundle/Controller/eleveController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

eleve:
    resource: "@EleveBundle/Resources/config/routing.yml"
    prefix:   /



app:
    resource: '@AppBundle/Controller/'
    type: annotation


